Add command principles and gem documentation
rubizza-camp/AgileCli pull request #22
Opened 2019-08-07 17:14 UTC by mirterious

# PR Details

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-08-07 17:36 UTC, artem-starovoitov approved these changes

2019-08-08 06:28 UTC, nieisnuje requested changes

2019-08-08 06:28 UTC, nieisnuje commented on client/lib/agile/commands/principles.rb
> +      say "Our highest priority is to satisfy the customer
Move this text to separate file

2019-08-08 06:59 UTC, nieisnuje approved these changes

2019-08-08 07:24 UTC, elishved approved these changes

2019-08-08 07:24 UTC, Berendor approved these changes

2019-08-08 07:24 UTC, merged