command manifest
rubizza-camp/AgileCli pull request #44
Opened 2019-08-14 06:02 UTC by epfeen

# PR Details

https://trello.com/c/4WpZUOdi/62-add-manifest-command

## Description

## Related Issue

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-08-14 06:30 UTC, nieisnuje requested changes

2019-08-14 06:30 UTC, nieisnuje commented on client/lib/agile/assets/manifest.txt
> +Values:
Manifesto:
https://agilemanifesto.org/

2019-08-14 06:30 UTC, nieisnuje commented on client/lib/agile/commands/manifest.rb
> +    desc Rainbow("manifest").cornflower, Rainbow("Shows manifest").darkgoldenrod
manifesto not manifest

2019-08-15 10:19 UTC, Berendor commented on client/lib/agile/assets/manifest.txt
> +Values:
```suggestion
Manifesto for Agile Software Development
```

2019-08-15 10:19 UTC, Berendor commented on client/lib/agile/commands/manifest.rb
> +    desc Rainbow("manifest").cornflower, Rainbow("Shows manifest").darkgoldenrod
```suggestion
    desc Rainbow("manifesto").cornflower, Rainbow("Shows manifest").darkgoldenrod
```

2019-08-15 12:17 UTC, closed without merging