add config file to gem
rubizza-camp/AgileCli pull request #48
Opened 2019-08-14 16:06 UTC by mirterious

# PR Details

## Description

## Related Issue

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-08-14 18:32 UTC, nieisnuje requested changes

2019-08-14 18:32 UTC, nieisnuje commented on client/lib/agile/commands/login.rb
> +      create_config_file
Если мы храним в конфиге url сервера, то как-то надо его доставать до логина. Чтобы при логине уже знать, куда обращаться

2019-08-14 20:35 UTC, mirterious commented on client/lib/agile/commands/login.rb
> +      create_config_file
Про логине мы всегда обращаемся на github

2019-08-15 06:41 UTC, artem-starovoitov approved these changes

2019-08-15 07:01 UTC, nieisnuje approved these changes

2019-08-15 07:05 UTC, elishved approved these changes

2019-08-15 07:05 UTC, merged