login
rubizza-camp/AgileCli pull request #65
Opened 2019-08-22 20:38 UTC by epfeen

# PR Details

## Description

## Related Issue

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-08-22 21:58 UTC, mirterious requested changes

2019-08-22 21:58 UTC, mirterious commented on .idea/.gitignore
>  /workspace.xml
Почему бы не удалить эту папку, перенести gitignore в корень репозитория и изменить его содержание?

2019-08-23 13:20 UTC, Berendor approved these changes

2019-08-23 13:25 UTC, mirterious approved these changes

2019-08-23 13:27 UTC, merged